[package]
name = "translit"
authors.workspace = true
version.workspace = true
edition = "2024"

[lib]
name = "translit"
path = "src/lib.rs"

[[bin]]
name = "futhorc"
path = "src/futhorc.rs"

[[bin]]
name = "tengwar"
path = "src/tengwar.rs"

[dependencies]
itertools.workspace = true
lazy_static.workspace = true
unicode-normalization.workspace = true
xml.workspace = true
