name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
          lfs: true

      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2.9.2

      - name: Test
        run: cargo test --workspace --exclude namegen-webui

  build-webui:
    uses: ./.github/workflows/build-webui.yml

  build-cli:
    uses: ./.github/workflows/build-cli.yml
    with:
      target: x86_64-unknown-linux-musl
      os: ubuntu-latest
